name: Test Discord Webhook

on:
  workflow_dispatch:  # 수동 실행 가능
  # schedule:
  #   - cron: "*/10 * * * *"   # 10분마다 실행 (테스트 끝나면 주석 해제)

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send test message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content":"✅ GitHub Actions에서 디스코드 웹훅 테스트 성공!"}' \
          ${{ secrets.DISCORD_WEBHOOK }}
