name: Node.js Discord Test

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"   # 10분마다 (UTC 기준!)

permissions:
  contents: write   # ← state.json을 커밋/푸시하려면 필요

jobs:
  send-message:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}  # 시크릿(웹훅)
      LUNLUN: ${{ vars.LUNLUN }}     
      LUNLUN_LIST: user1,user2,user3                  # 변수(감시할 유저)
      # NITTER_BASE: https://nitter.net                # 필요시 커스터마이즈

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0        # 커밋 푸시에 안전

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Debug runtime
        run: |
          node -v
          node -p "typeof fetch, typeof File"
          npm ls undici || true

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run script (fetch & maybe write state.json)
        run: node index.js

      - name: Commit state.json if changed
        run: |
          if [ -n "$(git status --porcelain state.json)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state.json
            git commit -m "chore: update state.json"
            git push
          else
            echo "No state change to commit."
          fi