name: Secret Sanity Check
on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}   # ← Job 레벨에서 주입

    steps:
      - name: Confirm secret presence (bash)
        run: |
          if [ -z "$DISCORD_WEBHOOK" ]; then
            echo "❌ MISSING: DISCORD_WEBHOOK"; exit 1;
          else
            echo "✅ PRESENT: DISCORD_WEBHOOK";
          fi

      - name: Confirm in Node context too
        run: node -e "console.log('Node sees DISCORD_WEBHOOK =', Boolean(process.env.DISCORD_WEBHOOK))"
